# car_groups.py

make_model_dict = {
    "Economy": [
        "Ford Escape", "Ford Puma", "Holden Acadia",
        "Holden Calais", "Holden Colorado", "Holden Equinox", "Holden Trailblazer",
        "Honda CR-V", "Honda Civic", "Honda HR-V", "Honda Integra",
        "Hyundai Genesis", "Hyundai I30", "Hyundai Iload", "Hyundai Imax",
        "Hyundai Kona", "Hyundai Santa", "Hyundai Sonata", "Hyundai Tucson",
        "Hyundai Venue", "Jeep Grand", "Kia Cerato", "Kia Sorento",
        "Kia Sportage", "Kia Stonic", "LDV D90", "LDV G10", "LDV G10+",
        "LDV T60", "LDV V80", "MG HS", "MG ZS",
        "MG ZST", "Mazda BT-50", "Mazda CX-3", "Mazda CX-5", "Mazda MX-30",
        "Mazda MX-5", 
        "Mini 5D", "Mini Cabrio", "Mini Clubman", "Mini Cooper", "Mini Countryman",
        "Mini Coupe", "Mini Paceman", "Mitsubishi ASX", "Mitsubishi Eclipse",
        "Mitsubishi Express", "Mitsubishi Outlander", "Mitsubishi Triton",
        "Nissan 350Z", "Nissan Navara", "Nissan Pathfinder", "Nissan Patrol",
        "Nissan Qashqai", "Nissan X-Trail", "Renault Kadjar", "Renault Koleos",
        "Renault Trafic", "Skoda Rapid", "Skoda Scala", "Skoda Superb",
        "Subaru BRZ", "Subaru Forester", "Subaru Levorg", "Subaru Outback",
        "Subaru XV", "Suzuki Ignis", "Suzuki Sierra", "Suzuki Swift",
        "Suzuki Vitara", "Toyota 86", "Toyota C-HR", "Toyota Camry",
        "Toyota Corolla", "Toyota HiAce", "Toyota Hiace", "Toyota Prius-C",
        "Volkswagen Caddy", "Volkswagen Crafter", "Volkswagen Golf",
        "Volkswagen Passat", "Volkswagen Scirocco", "Volkswagen T-Cross",
        "Volkswagen Transporter", "Volvo S60", "Volvo XC60", "Volvo XC90",

"BMW 116I", "BMW 118D", "BMW 120D", "BMW 125I", "BMW 135I",
        "BMW 316I", "BMW 318I", "BMW 320CI", "BMW 320D", "BMW 320I",
        "BMW 323I", "BMW 325I", "BMW 330CI", "BMW 330D", "BMW 525I",

 "Mercedes-Benz 190", "Mercedes-Benz A170", "Mercedes-Benz A190",
        "Mercedes-Benz B180", "Mercedes-Benz B250", "Mercedes-Benz C180",
        "Mercedes-Benz C230", "Mercedes-Benz CLC200", "Mercedes-Benz CLK280",
        "Mercedes-Benz CLK320", "Mercedes-Benz E240", "Mercedes-Benz GL320",
        "Mercedes-Benz MB100", "Mercedes-Benz ML320", "Mercedes-Benz ML500",
        "Mercedes-Benz R300", "Mercedes-Benz R320", "Mercedes-Benz S430",

 "Lexus ES300", "Lexus RX330"
    ],

    "Premium": [
"Audi A1", "Audi A3", "Audi A4", "Audi A6", "Audi A8",
        "BMW 118I", "BMW 120I", "BMW 218D", "BMW 218I", "BMW 220D",
        "BMW 220I", "BMW 225I", "BMW 228I", "BMW 328I", "BMW 335I",
        "BMW 420D", "BMW 520D", "BMW 530I", "BMW 740LI", "BMW I3",
        "BMW X1", "BMW X5",  

"Mercedes-Benz 420", "Mercedes-Benz B200", "Mercedes-Benz C220",
        "Mercedes-Benz C250", "Mercedes-Benz CLA200", "Mercedes-Benz CLK500",
        "Mercedes-Benz CLS350", "Mercedes-Benz CLS500", "Mercedes-Benz E250",
        "Mercedes-Benz E350", "Mercedes-Benz E500", "Mercedes-Benz GL500",
        "Mercedes-Benz GLA180", "Mercedes-Benz GLA200", "Mercedes-Benz GLA220",
        "Mercedes-Benz GLA250", "Mercedes-Benz ML250", "Mercedes-Benz ML300",
        "Mercedes-Benz ML350", "Mercedes-Benz SL350", "Mercedes-Benz SLK350",
        "Mercedes-Benz Sprinter", "Mercedes-Benz Viano", "Mercedes-Benz Vito",

 "Lexus CT200H", "Lexus IS250", "Lexus IS250C",
        "Lexus LX470", "Lexus NX200T", "Lexus RX270",
      
"Audi A5", "Audi A7", "Audi Q2", "Audi Q3", "Audi Q5", "Audi Q7",
        "Audi RS3", "Audi S3", "Audi S5", "Audi SQ5", "Audi TT",
        "BMW 128TI", "BMW 230I", "BMW 340I", "BMW 420I", "BMW 428I",
        "BMW 430I", "BMW 435I", "BMW 530D", "BMW M135I", "BMW M140I",
        "BMW M235I", "BMW M240I", "BMW X2", "BMW X3", "BMW X4", "BMW X6",
        "BMW Z4", "Ford Endura", "Ford Everest", "Ford Mustang", "Ford Ranger",
        "Ford Transit", "GWM Haval", "GWM ORA", "GWM Tank", "GWM UTE",
        "Holden Monaro", "Holden UTE", "Hyundai Ioniq", "Hyundai Staria",
        "Isuzu D-MAX", "Isuzu MU-X", "Jeep Compass", "Jeep Wrangler",
        "Kia Carnival", "Kia Niro", "Kia Seltos", "Kia Stinger", "Land Rover",
        "Lexus CT", "Lexus ES250", "Lexus ES300H", "Lexus ES350",
        "Lexus GS250", "Lexus GS350", "Lexus GS450H", "Lexus IS200T",
        "Lexus IS300", "Lexus IS300H", "Lexus IS350", "Lexus LS460",
        "Lexus NX300", "Lexus NX300H", "Lexus RC200T", "Lexus RC350",
        "Lexus RX300", "Lexus RX350", "Lexus RX450H", "Lexus SC430",
        "Lexus UX200", "Mazda CX-30", "Mazda CX-8", "Mazda CX-9",
        "Mercedes-Benz 560", "Mercedes-Benz A180", "Mercedes-Benz A200",
        "Mercedes-Benz A250", "Mercedes-Benz A35", "Mercedes-Benz A45",
        "Mercedes-Benz C200", "Mercedes-Benz C300", "Mercedes-Benz C350",
        "Mercedes-Benz CLA250", "Mercedes-Benz CLA45", "Mercedes-Benz CLK63",
        "Mercedes-Benz CLS250", "Mercedes-Benz E200", "Mercedes-Benz E220",
        "Mercedes-Benz E400", "Mercedes-Benz E55", "Mercedes-Benz GLA45",
        "Mercedes-Benz GLC200", "Mercedes-Benz GLC220", "Mercedes-Benz GLC250",
        "Mercedes-Benz GLC350", "Mercedes-Benz GLE250", "Mercedes-Benz GLE350",
        "Mercedes-Benz ML400", "Mercedes-Benz ML63", "Mercedes-Benz S350",
        "Mercedes-Benz SL500", "Mercedes-Benz V250", "Mercedes-Benz Valente",
        "Mercedes-Benz X250", "Mercedes-Benz X350", "Mini 3D", "Mini Convertible",
        "Mitsubishi Pajero", "Nissan 300ZX", "Nissan 370Z", "Nissan Leaf",
        "Porsche Macan", "Renault Arkana", "Renault Captur", "Renault Master",
        "Skoda Kamiq", "Skoda Karoq", "Skoda Kodiaq", "Skoda Octavia",
        "Subaru WRX", "Suzuki Jimny", "Suzuki S-Cross", "Toyota FJ",
        "Toyota Fortuner", "Toyota GR", "Toyota GR86", "Toyota Granvia",
        "Toyota Hilux", "Toyota Kluger", "Toyota Landcruiser", "Toyota RAV4",
        "Volkswagen Amarok", "Volkswagen Caravelle", "Volkswagen Multivan",
        "Volkswagen T-ROC", "Volkswagen Tiguan", "Volkswagen Touareg", "Volvo XC40"
    ],

    "Super_luxury": [
        "Audi E-Tron", "Audi R8", "Audi RS", "Audi RS4", "Audi RS5", "Audi RS6",
        "Audi SQ7", "Audi SQ8", "BMW 5", "BMW I4", "BMW IX", "BMW M8",
        "BMW X7", "Holden HDT", "LDV Mifa", "Lexus LC500", "Lexus LX450D",
        "Lexus LX500D", "Lexus LX570", "Lexus LX600", "Lexus RX500H",
        "Mercedes-Benz AMG", "Mercedes-Benz C63", "Mercedes-Benz CLS53",
        "Mercedes-Benz E53", "Mercedes-Benz E63", "Mercedes-Benz EQB",
        "Mercedes-Benz EQC", "Mercedes-Benz EQS53", "Mercedes-Benz G63",
        "Mercedes-Benz GLC63", "Mercedes-Benz GLE", "Mercedes-Benz GLE63",
        "Mercedes-Benz GLS", "Mercedes-Benz Maybach", "Mercedes-Benz S450",
        "Mercedes-Benz S450L", "Mercedes-Benz S63", "Mercedes-Benz V",
        "Nissan GT-R", "Porsche 718", "Porsche 911", "Porsche Cayman",
        "Porsche Taycan", "Toyota Coaster"
    ],

    "Luxury": [
        "Audi Q8", "Audi S4", "Audi SQ2", "BMW 2", "BMW 330I", "BMW 730D",
        "BMW 740I", "BMW M2", "BMW M3", "BMW M340I", "BMW M4", "BMW M440I",
        "BMW M5", "BMW M6", "Ford F250", "Hyundai Palisade", "Jeep Gladiator",
        "Kia EV6", "Lexus NX250", "Lexus NX350", "Lexus NX350H", "Lexus RC",
        "Lexus RX350L", "Lexus RX450HL", "Mercedes-Benz C43", "Mercedes-Benz CLA",
        "Mercedes-Benz CLA35", "Mercedes-Benz E300", "Mercedes-Benz EQA",
        "Mercedes-Benz G350", "Mercedes-Benz GL63", "Mercedes-Benz GLA",
        "Mercedes-Benz GLA35", "Mercedes-Benz GLB", "Mercedes-Benz GLC",
        "Mercedes-Benz GLC300", "Mercedes-Benz GLC43", "Mercedes-Benz GLE300",
        "Mercedes-Benz GLE400", "Mercedes-Benz GLE43", "Mercedes-Benz GLE450",
        "Mercedes-Benz GLS350", "Mercedes-Benz GLS500", "Mercedes-Benz Marco",
        "Mercedes-Benz S65", "Mercedes-Benz SL55", "Mercedes-Benz SLC",
        "Nissan Z", "Porsche Boxster", "Porsche Cayenne", "Porsche Panamera",
        "Toyota Supra", "Volkswagen Arteon", "Volvo C40"
    ],

    "Budget": [
        
        "Ford Courier", "Ford Ecosport", "Ford Fairlane", "Ford Fairmont",
        "Ford Falcon", "Ford Festiva", "Ford Fiesta", "Ford Focus",
        "Ford Kuga", "Ford Laser", "Ford Maverick", "Ford Mondeo",
        "Ford Territory", "GWM Steed", "Holden Adventra", "Holden Astra",
        "Holden Barina", "Holden Caprice", "Holden Captiva", "Holden Cascada",
        "Holden Combo", "Holden Commodore", "Holden Crewman", "Holden Cruze",
        "Holden Epica", "Holden Jackaroo", "Holden Malibu", "Holden Rodeo",
        "Holden Statesman", "Holden Trax", "Holden Vectra", "Holden Viva",
        "Honda Accord", "Honda CR-Z", "Honda City", "Honda Jazz", "Honda Odyssey",
        "Hyundai Accent", "Hyundai Elantra", "Hyundai Getz", "Hyundai I20",
        "Hyundai I40", "Hyundai I45", "Hyundai IX35", "Hyundai Terracan",
        "Hyundai Trajet", "Hyundai Veloster", "Jeep Cherokee", "Jeep Commander",
        "Jeep Patriot", "Jeep Renegade", "Kia Grand", "Kia K2700", "Kia Optima",
        "Kia Picanto", "Kia RIO", "Kia Rondo", "Kia Soul", "Kia Spectra",
        "MG 3", "MG 6", "MG F", "MG MG3",
        "Mazda 121", "Mazda 2", "Mazda 3", "Mazda 323", "Mazda 6", "Mazda B2500",
        "Mazda B4000", "Mazda CX-7", "Mazda E2000", "Mazda MPV", "Mazda RX-8",
        "Mazda Tribute",
        "Mitsubishi 380", "Mitsubishi Challenger", "Mitsubishi Lancer",
        "Mitsubishi Magna", "Mitsubishi Mirage", "Mitsubishi Verada",
        "Nissan Almera", "Nissan Altima", "Nissan Dualis", "Nissan Juke",
        "Nissan Maxima", "Nissan Micra", "Nissan Murano", "Nissan Pulsar",
        "Nissan Tiida", "Renault Clio", "Renault Kangoo", "Renault Laguna",
        "Renault Megane", "Skoda Fabia", "Skoda Roomster", "Subaru Impreza",
        "Subaru Liberty", "Subaru Tribeca", "Suzuki APV", "Suzuki Alto",
        "Suzuki Baleno", "Suzuki Celerio", "Suzuki Grand", "Suzuki Kizashi",
        "Suzuki SX4", "Suzuki XL-7", "Toyota Aurion", "Toyota Avalon",
        "Toyota Avensis", "Toyota Celica", "Toyota Echo", "Toyota Prius",
        "Toyota Tarago", "Toyota Yaris", "Volkswagen Beetle", "Volkswagen CC",
        "Volkswagen EOS", "Volkswagen Jetta", "Volkswagen Polo",
        "Volvo C30", "Volvo S40", "Volvo V40", "Volvo V50", "Volvo V60",
        "Volvo XC70"
    ]
}
